CREATE TABLE IF NOT EXISTS autographs (
    id SERIAL PRIMARY KEY,
    instagram_url VARCHAR(500) UNIQUE NOT NULL,
    encrypted_code TEXT NOT NULL,
    raw_code VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
