services:
  - type: web
    name: autograph
    env: python
    buildCommand: |
      python -m pip install -r WebApp/requirements.txt
      cp -r WebApp/* .
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SSL_ENABLED
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: SENTRY_DSN
        value: https://07ce61424d89527953a4214e0d11de94@o4509188028432384.ingest.de.sentry.io/4509188030595152
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 