"""Initial migration

Revision ID: 0c6ef0247d84
Revises: 5b9dc3545cdc
Create Date: 2025-04-18 23:01:45.259119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6ef0247d84'
down_revision = '5b9dc3545cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autographs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_url', sa.String(length=500), nullable=False),
    sa.Column('encrypted_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autographs')
    # ### end Alembic commands ###
